services:
  frontend:
    build:
      context: ./frontend
      target: dev-envs
    container_name: frontend
    ports:
      - "8887:3000"
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
